### ISSUE TITLE
Versão

### ISSUE THREAD

**Issue by Valdriano** [pictos/RotaComMapa#1]
Bom dia, gostaria de sabe qual e a versão do android, que suporta esse mapa, pois tentei compilar e nao deu certo.

**Comment by pictos** [comment]
Olá Valdriano, então não setei API máxima, apenas a miníma(que é a API15)*.
Você lembrou de obter as chaves de acesso das APIs? 

* Para ver a versão de API suportada por um APP basta ir no AndroidManifest.xml ://github.com/pictos/RotaComMapa/blob/master/RouteMap/RouteMap.Android/Properties/AndroidManifest.xml

;D

**Comment by Valdriano** [comment]
Pictos, criei um do zero usando as mesmas coisa que voce fez e deu certo, ou duvida, eu so consigo montar rota por estado? ou eu posso montar uma local, tipo usando o a minha cidade de um bairro para outro.

**Comment by pictos** [comment]
Valdriano, você consegue criar rotas utilizando qualquer tipo de endereço (rua, bairro, cidade,estado,país), acredito que até localização (CEFET,UFMG, USP,etc). Para maiores informações sobre isso basta consultar a documentação da API. Inclusive a URL da requisição pode ter ainda mais parâmetros.

Fechado esse Issue.

**Comment by Valdriano** [comment]
obrigado pelas resposta, desculpe incomoda mais uma vez, gostaria de saber como eu faria para implementar este mapa no IOS.

**Comment by pictos** [comment]
Não é incomodo nenhum! Tem que criar um CustomRenderer no IoS, assim como fiz no Android... Não fiz pro IoS pq não tenho como testar :/. Vou implementar e subir, mas n posso garantir pq n tenho como testar. Aviso por aqui quando eu subir

**Comment by Valdriano** [comment]
ta beleza eu vou te seguir aqui pra min fica atento a essa novidade, eu tenho um mac aqui pra min fazer teste em IOS

**Comment by pictos** [comment]
Subi pro IoS, mas n sei se vai funcionar hehe
