### ISSUE TITLE
Error APT0000 no Build

### ISSUE THREAD

**Issue by gravitpt** [pictos/RotaComMapa#2]
Caros, ao tentar rodar deu o erro abaixo, não tenho a minima noção o que pode ser, vcs podem me ajudar?

 Error APT0000:  Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'. (APT0000) (RouteMap.Android)

**Comment by pictos** [comment]
Baixe o projeto e recompile para que o VS baixe todas referências.
Se na hora de debugar ainda der erro delete as pastas bin e obj da solução, limpe a solução  e recompile.

**Comment by pictos** [comment]
1 semana sem resposta. Issue fechada.
